export const MESSAGES_REF = '/messages'
export const PROFILE_REF = '/profile'
export const MESSAGES_LOCATIONS_REF = '/messages-locations'
export const NOTIFICATIONS_REF = '/notifications'
export const LIKES_REF = '/likes'
export const CHATS_REF = '/chats'
export const CHAT_MESSAGES_REF = '/chat-messages'
