export const MESSAGES_REF = '/messages'
export const PROFILE_REF = '/profile'
export const MESSAGES_LOCATIONS_REF = '/messages-locations'
export const LIKES_REF = '/likes'
export const ACHIEVEMENTS_REF = '/achievements'
export const OWNED_ACHIEVEMENTS_REF = '/owned-achievements'
